CREATE TABLE `jemline2`.`bubbles` 
( `bubbleId` INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
`title` VARCHAR(256) NOT NULL , 
`author` VARCHAR(256) NOT NULL , 
`message` VARCHAR(1024) NULL );
